/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffSwapsRouteImport } from './routes/staff.swaps'
import { Route as StaffShiftsRouteImport } from './routes/staff.shifts'
import { Route as StaffRequestLeaveRouteImport } from './routes/staff.request-leave'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffLeaveStatusRouteImport } from './routes/staff.leave-status'
import { Route as StaffHelpRouteImport } from './routes/staff.help'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffAvailabilityRouteImport } from './routes/staff.availability'
import { Route as ManagerUsersRouteImport } from './routes/manager.users'
import { Route as ManagerSwapsRouteImport } from './routes/manager.swaps'
import { Route as ManagerStaffRouteImport } from './routes/manager.staff'
import { Route as ManagerShiftTemplatesRouteImport } from './routes/manager.shift-templates'
import { Route as ManagerSettingsRouteImport } from './routes/manager.settings'
import { Route as ManagerRulesRouteImport } from './routes/manager.rules'
import { Route as ManagerRosterRouteImport } from './routes/manager.roster'
import { Route as ManagerProfileRouteImport } from './routes/manager.profile'
import { Route as ManagerPlanningRouteImport } from './routes/manager.planning'
import { Route as ManagerLeaveRouteImport } from './routes/manager.leave'
import { Route as ManagerHelpRouteImport } from './routes/manager.help'
import { Route as ManagerGenerateRouteImport } from './routes/manager.generate'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as ManagerConflictsRouteImport } from './routes/manager.conflicts'
import { Route as ManagerAvailabilityRouteImport } from './routes/manager.availability'
import { Route as ManagerAssignmentRouteImport } from './routes/manager.assignment'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSwapsRoute = StaffSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => StaffRoute,
} as any)
const StaffShiftsRoute = StaffShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRequestLeaveRoute = StaffRequestLeaveRouteImport.update({
  id: '/request-leave',
  path: '/request-leave',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLeaveStatusRoute = StaffLeaveStatusRouteImport.update({
  id: '/leave-status',
  path: '/leave-status',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHelpRoute = StaffHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAvailabilityRoute = StaffAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => StaffRoute,
} as any)
const ManagerUsersRoute = ManagerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSwapsRoute = ManagerSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerStaffRoute = ManagerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerShiftTemplatesRoute = ManagerShiftTemplatesRouteImport.update({
  id: '/shift-templates',
  path: '/shift-templates',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerRulesRoute = ManagerRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerRosterRoute = ManagerRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProfileRoute = ManagerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPlanningRoute = ManagerPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerLeaveRoute = ManagerLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerHelpRoute = ManagerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerGenerateRoute = ManagerGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerConflictsRoute = ManagerConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAvailabilityRoute = ManagerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAssignmentRoute = ManagerAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => ManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/manager/assignment': typeof ManagerAssignmentRoute
  '/manager/availability': typeof ManagerAvailabilityRoute
  '/manager/conflicts': typeof ManagerConflictsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/generate': typeof ManagerGenerateRoute
  '/manager/help': typeof ManagerHelpRoute
  '/manager/leave': typeof ManagerLeaveRoute
  '/manager/planning': typeof ManagerPlanningRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/roster': typeof ManagerRosterRoute
  '/manager/rules': typeof ManagerRulesRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/shift-templates': typeof ManagerShiftTemplatesRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/manager/swaps': typeof ManagerSwapsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/staff/availability': typeof StaffAvailabilityRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/help': typeof StaffHelpRoute
  '/staff/leave-status': typeof StaffLeaveStatusRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/request-leave': typeof StaffRequestLeaveRoute
  '/staff/shifts': typeof StaffShiftsRoute
  '/staff/swaps': typeof StaffSwapsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/manager/assignment': typeof ManagerAssignmentRoute
  '/manager/availability': typeof ManagerAvailabilityRoute
  '/manager/conflicts': typeof ManagerConflictsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/generate': typeof ManagerGenerateRoute
  '/manager/help': typeof ManagerHelpRoute
  '/manager/leave': typeof ManagerLeaveRoute
  '/manager/planning': typeof ManagerPlanningRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/roster': typeof ManagerRosterRoute
  '/manager/rules': typeof ManagerRulesRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/shift-templates': typeof ManagerShiftTemplatesRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/manager/swaps': typeof ManagerSwapsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/staff/availability': typeof StaffAvailabilityRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/help': typeof StaffHelpRoute
  '/staff/leave-status': typeof StaffLeaveStatusRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/request-leave': typeof StaffRequestLeaveRoute
  '/staff/shifts': typeof StaffShiftsRoute
  '/staff/swaps': typeof StaffSwapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/manager/assignment': typeof ManagerAssignmentRoute
  '/manager/availability': typeof ManagerAvailabilityRoute
  '/manager/conflicts': typeof ManagerConflictsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/generate': typeof ManagerGenerateRoute
  '/manager/help': typeof ManagerHelpRoute
  '/manager/leave': typeof ManagerLeaveRoute
  '/manager/planning': typeof ManagerPlanningRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/roster': typeof ManagerRosterRoute
  '/manager/rules': typeof ManagerRulesRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/shift-templates': typeof ManagerShiftTemplatesRoute
  '/manager/staff': typeof ManagerStaffRoute
  '/manager/swaps': typeof ManagerSwapsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/staff/availability': typeof StaffAvailabilityRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/help': typeof StaffHelpRoute
  '/staff/leave-status': typeof StaffLeaveStatusRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/request-leave': typeof StaffRequestLeaveRoute
  '/staff/shifts': typeof StaffShiftsRoute
  '/staff/swaps': typeof StaffSwapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/staff'
    | '/manager/assignment'
    | '/manager/availability'
    | '/manager/conflicts'
    | '/manager/dashboard'
    | '/manager/generate'
    | '/manager/help'
    | '/manager/leave'
    | '/manager/planning'
    | '/manager/profile'
    | '/manager/roster'
    | '/manager/rules'
    | '/manager/settings'
    | '/manager/shift-templates'
    | '/manager/staff'
    | '/manager/swaps'
    | '/manager/users'
    | '/staff/availability'
    | '/staff/dashboard'
    | '/staff/help'
    | '/staff/leave-status'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/request-leave'
    | '/staff/shifts'
    | '/staff/swaps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/staff'
    | '/manager/assignment'
    | '/manager/availability'
    | '/manager/conflicts'
    | '/manager/dashboard'
    | '/manager/generate'
    | '/manager/help'
    | '/manager/leave'
    | '/manager/planning'
    | '/manager/profile'
    | '/manager/roster'
    | '/manager/rules'
    | '/manager/settings'
    | '/manager/shift-templates'
    | '/manager/staff'
    | '/manager/swaps'
    | '/manager/users'
    | '/staff/availability'
    | '/staff/dashboard'
    | '/staff/help'
    | '/staff/leave-status'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/request-leave'
    | '/staff/shifts'
    | '/staff/swaps'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/manager'
    | '/staff'
    | '/manager/assignment'
    | '/manager/availability'
    | '/manager/conflicts'
    | '/manager/dashboard'
    | '/manager/generate'
    | '/manager/help'
    | '/manager/leave'
    | '/manager/planning'
    | '/manager/profile'
    | '/manager/roster'
    | '/manager/rules'
    | '/manager/settings'
    | '/manager/shift-templates'
    | '/manager/staff'
    | '/manager/swaps'
    | '/manager/users'
    | '/staff/availability'
    | '/staff/dashboard'
    | '/staff/help'
    | '/staff/leave-status'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/request-leave'
    | '/staff/shifts'
    | '/staff/swaps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/swaps': {
      id: '/staff/swaps'
      path: '/swaps'
      fullPath: '/staff/swaps'
      preLoaderRoute: typeof StaffSwapsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/shifts': {
      id: '/staff/shifts'
      path: '/shifts'
      fullPath: '/staff/shifts'
      preLoaderRoute: typeof StaffShiftsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/request-leave': {
      id: '/staff/request-leave'
      path: '/request-leave'
      fullPath: '/staff/request-leave'
      preLoaderRoute: typeof StaffRequestLeaveRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/leave-status': {
      id: '/staff/leave-status'
      path: '/leave-status'
      fullPath: '/staff/leave-status'
      preLoaderRoute: typeof StaffLeaveStatusRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/help': {
      id: '/staff/help'
      path: '/help'
      fullPath: '/staff/help'
      preLoaderRoute: typeof StaffHelpRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/availability': {
      id: '/staff/availability'
      path: '/availability'
      fullPath: '/staff/availability'
      preLoaderRoute: typeof StaffAvailabilityRouteImport
      parentRoute: typeof StaffRoute
    }
    '/manager/users': {
      id: '/manager/users'
      path: '/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/swaps': {
      id: '/manager/swaps'
      path: '/swaps'
      fullPath: '/manager/swaps'
      preLoaderRoute: typeof ManagerSwapsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/staff': {
      id: '/manager/staff'
      path: '/staff'
      fullPath: '/manager/staff'
      preLoaderRoute: typeof ManagerStaffRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/shift-templates': {
      id: '/manager/shift-templates'
      path: '/shift-templates'
      fullPath: '/manager/shift-templates'
      preLoaderRoute: typeof ManagerShiftTemplatesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/rules': {
      id: '/manager/rules'
      path: '/rules'
      fullPath: '/manager/rules'
      preLoaderRoute: typeof ManagerRulesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/roster': {
      id: '/manager/roster'
      path: '/roster'
      fullPath: '/manager/roster'
      preLoaderRoute: typeof ManagerRosterRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/profile': {
      id: '/manager/profile'
      path: '/profile'
      fullPath: '/manager/profile'
      preLoaderRoute: typeof ManagerProfileRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/planning': {
      id: '/manager/planning'
      path: '/planning'
      fullPath: '/manager/planning'
      preLoaderRoute: typeof ManagerPlanningRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/leave': {
      id: '/manager/leave'
      path: '/leave'
      fullPath: '/manager/leave'
      preLoaderRoute: typeof ManagerLeaveRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/help': {
      id: '/manager/help'
      path: '/help'
      fullPath: '/manager/help'
      preLoaderRoute: typeof ManagerHelpRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/generate': {
      id: '/manager/generate'
      path: '/generate'
      fullPath: '/manager/generate'
      preLoaderRoute: typeof ManagerGenerateRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/conflicts': {
      id: '/manager/conflicts'
      path: '/conflicts'
      fullPath: '/manager/conflicts'
      preLoaderRoute: typeof ManagerConflictsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/availability': {
      id: '/manager/availability'
      path: '/availability'
      fullPath: '/manager/availability'
      preLoaderRoute: typeof ManagerAvailabilityRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/assignment': {
      id: '/manager/assignment'
      path: '/assignment'
      fullPath: '/manager/assignment'
      preLoaderRoute: typeof ManagerAssignmentRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface ManagerRouteChildren {
  ManagerAssignmentRoute: typeof ManagerAssignmentRoute
  ManagerAvailabilityRoute: typeof ManagerAvailabilityRoute
  ManagerConflictsRoute: typeof ManagerConflictsRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerGenerateRoute: typeof ManagerGenerateRoute
  ManagerHelpRoute: typeof ManagerHelpRoute
  ManagerLeaveRoute: typeof ManagerLeaveRoute
  ManagerPlanningRoute: typeof ManagerPlanningRoute
  ManagerProfileRoute: typeof ManagerProfileRoute
  ManagerRosterRoute: typeof ManagerRosterRoute
  ManagerRulesRoute: typeof ManagerRulesRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerShiftTemplatesRoute: typeof ManagerShiftTemplatesRoute
  ManagerStaffRoute: typeof ManagerStaffRoute
  ManagerSwapsRoute: typeof ManagerSwapsRoute
  ManagerUsersRoute: typeof ManagerUsersRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAssignmentRoute: ManagerAssignmentRoute,
  ManagerAvailabilityRoute: ManagerAvailabilityRoute,
  ManagerConflictsRoute: ManagerConflictsRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerGenerateRoute: ManagerGenerateRoute,
  ManagerHelpRoute: ManagerHelpRoute,
  ManagerLeaveRoute: ManagerLeaveRoute,
  ManagerPlanningRoute: ManagerPlanningRoute,
  ManagerProfileRoute: ManagerProfileRoute,
  ManagerRosterRoute: ManagerRosterRoute,
  ManagerRulesRoute: ManagerRulesRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerShiftTemplatesRoute: ManagerShiftTemplatesRoute,
  ManagerStaffRoute: ManagerStaffRoute,
  ManagerSwapsRoute: ManagerSwapsRoute,
  ManagerUsersRoute: ManagerUsersRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface StaffRouteChildren {
  StaffAvailabilityRoute: typeof StaffAvailabilityRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffHelpRoute: typeof StaffHelpRoute
  StaffLeaveStatusRoute: typeof StaffLeaveStatusRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffRequestLeaveRoute: typeof StaffRequestLeaveRoute
  StaffShiftsRoute: typeof StaffShiftsRoute
  StaffSwapsRoute: typeof StaffSwapsRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAvailabilityRoute: StaffAvailabilityRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffHelpRoute: StaffHelpRoute,
  StaffLeaveStatusRoute: StaffLeaveStatusRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffRequestLeaveRoute: StaffRequestLeaveRoute,
  StaffShiftsRoute: StaffShiftsRoute,
  StaffSwapsRoute: StaffSwapsRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
