# Generated by Django 6.0.6 on 2026-06-28 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
